#!/usr/bin/env python3

# Author: <YOUR_NAME_HERE>
# CSC 574 Mini-Project 1
# eft-dh: encrypted file transfer using DH key exchange

# Import additional modules as needed.
import argparse
import sys
import socket
import os
from base64 import b64encode
from base64 import b64decode
from Crypto.Hash import SHA256
from Crypto.Cipher import AES
from Crypto.Util.Padding import pad
from Crypto.Util.Padding import unpad

# Diffie-Hellman Parameters
g=2
p=0x00cc81ea8157352a9e9a318aac4e33ffba80fc8da3373fb44895109e4c3ff6cedcc55c02228fccbd551a504feb4346d2aef47053311ceaba95f6c540b967b9409e9f0502e598cfc71327c5a455e2e807bede1e0b7d23fbea054b951ca964eaecae7ba842ba1fc6818c453bf19eb9c5c86e723e69a210d4b72561cab97b3fb3060b


def print_debug(*objects, sep=' ', end='\n', file=sys.stderr, flush=False):
    """
    When stdout is redirected, messages cannot be printed to stdout as they will be written to the file, not the console.
    Use this function to print debug messages to stderr.
    It supports all optional arguments of the print function, with the exception that file is overridden to stderr.

    IMPORTANT: This function cannot be used to display debug messages in the autograder environment.

    :param objects: Any non-keyword argument that can be converted to string.
    :param sep: String to separate objects. [Default: Space]
    :param end: String to append to the end. [Default: Newline]
    :param file: Not used. Overridden to sys.stderr.
    :param flush: Forcibly flush the stream.
    """

    print(objects, sep=sep, end=end, file=sys.stderr, flush=flush)


def read_file(buffer_len):
    """
    Wrapper function for reading from stdin.
    Use < to redirect a file to stdin.

    :param buffer_len: Number of bytes to read at once.
    :return: Raw bytes or None if buffer is empty.
    """

    return sys.stdin.buffer.read(buffer_len)


def write_file(data):
    """
    Wrapper function for writing a file to stdout.
    Use > to redirect stdout to a file.

    :param data: raw bytes.
    """

    sys.stdout.buffer.write(data)


def num_to_x_byte_str(num,numbytes):
    """
    Converts int to numbytes-byte string with a bunch of 0s in front of it
    IMPORTANT: This function should NOT be used when creating the string representation of the output of the
                diffie-hellman key agreement procedure before hashing it. Use create_final_dh_string instead.


    :param num: The number to be encoded.
    :param numbytes:  The total number of bytes the string should take.
    :return: decimal representation of num padded with zeros.
    """

    num = str(num)
    return (numbytes-len(num))*'0' + num


def create_final_dh_string(new_key):
    """
    Process the output of the diffie_hellman key into a hex string for use in generating the session key.
    IMPORTANT: This function should NOT be used when creating the string representation of A and B.
               Use num_to_x_byte_str instead.

    :param new_key: Diffie-Hellman Key
    :return: Hex string representation of new_key.
    """

    # Post-process the created key
    new_key_str = '%x' % new_key
    return new_key_str.encode('utf-8')


def server(port):
    """
    Server Code

    :param port: Port number to listen on.
    """

    serversocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    serversocket.bind(('', port))
    serversocket.listen(1)
    
    (clientsocket, address) = serversocket.accept()
    
    y1 = int(clientsocket.recv(384).decode('utf-8'))
    
    x2 = int.from_bytes(os.urandom(32), byteorder='big')
    y2 = pow(g, x2, p)

    clientsocket.sendall(num_to_x_byte_str(y2, 384).encode('utf-8'))
    
    k2 = pow(y1, x2, p)
    # print_debug("k2: " + str(k2))
    
    final_dh_string = create_final_dh_string(k2)
    
    session_key = SHA256.new(final_dh_string).digest()[:32]
    # print_debug(session_key)
    
    chunks = [] # empty list to store chunks of file data
    bytes_received = 0
    while bytes_received < 65535: # loop until max limit of 65535 bytes is reached
        length_bytes = clientsocket.recv(2) # receive first 2 bytes of message to get length of chunk
        if not length_bytes: # if no length received, exit loop
            break
        
        length = int.from_bytes(length_bytes, byteorder='big') # convert length to integer
        
        nonce = clientsocket.recv(16) # receive nonce
        tag = clientsocket.recv(16) # receive tag
        ciphertext = clientsocket.recv(length - 32) # receive chunk of file data        
        
        # pulled from pycryptodome documentation and slightly modified
        try:
            cipher = AES.new(session_key, AES.MODE_GCM, nonce=nonce)
            # print_debug("ciphertext: " + str(ciphertext))
            # print_debug("tag: " + str(tag))
            plaintext = cipher.decrypt_and_verify(ciphertext, tag)
            # decoded = plaintext.decode('utf-8')
            
            unpadded = unpad(plaintext, 16, style='pkcs7')
            chunks.append(unpadded) # append chunk to list
            bytes_received += (len(ciphertext) + 32) # update total bytes count    
        except Exception as e:
            sys.stderr.write("Error: integrity check failed.\n")
            sys.exit()
    
    file_data = b''.join(chunks)
    write_file(file_data) # write file data to stdout
    clientsocket.close()
    serversocket.close()
    
def client(addr, port):
    """
    Client Code

    :param addr: IP address of the server.
    :param port: Port to connect to.
    :return:
    """

    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((addr, port))
    
    x1 = int.from_bytes(os.urandom(32), byteorder='big')
    y1 = pow(g, x1, p)

    s.sendall(num_to_x_byte_str(y1, 384).encode('utf-8'))
 
    y2 = int(s.recv(384).decode('utf-8'))
    
    k1 = pow(y2, x1, p)
    # print_debug("k1: " + str(k1))
    
    final_dh_string = create_final_dh_string(k1)
    
    session_key = SHA256.new(final_dh_string).digest()[:32]
    # print_debug(session_key)
    
    try:        
        buffer_len = 1024
                
        while True:
            chunk = read_file(buffer_len)
            if not chunk:
                break
            
            padded = pad(chunk, 16, style='pkcs7')
            
            # create a cipher object
            cipher = AES.new(session_key, AES.MODE_GCM)
            
            # encrypt the padded chunk using cipher object and digest result
            ciphertext, tag = cipher.encrypt_and_digest(padded)
            
            #get nonce (iv) from cipher object
            nonce = cipher.nonce
            
            # send length of the encrypted data
            length = len(ciphertext) + 32
            length_bytes = length.to_bytes(2, byteorder='big')
            pdu = length_bytes + nonce + tag + ciphertext
            
            # print_debug("ciphertext: " + str(ciphertext))
            # print_debug("tag: " + str(tag))
            # send file data in chunks
            # print_debug("Chunks sent: " + str(len(encrypted)))
            # print_debug("Whats sent: " + str(pdu))
            s.sendall(pdu)
        
    except (ValueError, KeyError):
        sys.stderr.write("Error: integrity check failed.\n")
        sys.exit()
    finally:
        # print_debug("File sent. Terminating program.")
        s.close()


def parse_args():
    """
    Command Line Argument Parser

    :return: Argparse Namespace of identified command line arguments.
    """
    # Configure the argument parser.
    parser = argparse.ArgumentParser(description='Encrypted File Transfer using Diffie-Hellman Key Exchange Protocol')
    server_group = parser.add_argument_group('server_group', 'Server mode options')
    server_group.add_argument('-l', dest='server_port', action='store', help='Server mode with port')
    client_group = parser.add_argument_group('client_group', 'Client mode options')
    client_group.add_argument('client_ip_address', nargs='?')
    client_group.add_argument('client_port', nargs='?')

    # Parse arguments.
    args = parser.parse_args()

    # Check if arguments are valid.
    args_ok = ((args.server_port is None) and (args.client_ip_address is not None and args.client_port is not None)) or \
              ((args.server_port is not None) and (args.client_ip_address is None and args.client_port is None))

    # If not, show usage message and exit.
    if not args_ok:
        print("./eft-dh [-l SERVER_PORT > OUTPUT FILE] [CLIENT_IP_ADDRESS CLIENT_PORT < INPUT_FILE]")
        sys.exit(0)

    # Otherwise return the args.
    return args


def main():
    # Parse Arguments
    args = parse_args()

    # Launch the client or server depending on the arguments received.
    if args.server_port is not None:
        port = int(args.server_port)
        server(port)
    else:
        addr = args.client_ip_address
        port = int(args.client_port)
        client(addr, port)


if __name__ == "__main__":
    main()
